# Generated by Django 2.2.12 on 2021-03-25 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0018_academicstatistics_number_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('year', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Reporte Anuales',
                'verbose_name_plural': 'Listado de Reportes',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='TypeReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de Reporte')),
            ],
            options={
                'verbose_name': 'Tipo de Reporte',
                'verbose_name_plural': 'Listado de Reportes',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='UnpublishedLectures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título de Conferencia')),
                ('congress', models.CharField(max_length=200, verbose_name='Nombre de Congreso')),
                ('city', models.CharField(max_length=30, null=True, verbose_name='Ciudad')),
                ('country', models.CharField(max_length=30, null=True, verbose_name='País')),
                ('institute', models.CharField(max_length=150, null=True, verbose_name='Institución')),
                ('type_job', models.CharField(max_length=30, null=True, verbose_name='Tipo de Investigación')),
                ('annual_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unpublishedlectures', to='production.AnnualReport')),
                ('type_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unpublishedlectures', to='production.TypeReport')),
                ('user', models.ManyToManyField(related_name='unpublishedlectures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre de Actividad')),
                ('institute', models.CharField(max_length=250, verbose_name='Instituto')),
                ('type_activity', models.CharField(max_length=50, verbose_name='Tipo de Actividad')),
                ('hours', models.IntegerField(verbose_name='Número de Horas')),
                ('annual_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachertraining', to='production.AnnualReport')),
                ('type_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachertraining', to='production.TypeReport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachertraining', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formación Docente',
                'verbose_name_plural': 'Listado de Formación Docente',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ResearchProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de Proyecto')),
                ('participants', models.CharField(max_length=255, null=True, verbose_name='Participantes')),
                ('approval', models.CharField(max_length=100, verbose_name='Fecha de Aprobación')),
                ('validity', models.CharField(max_length=100, null=True, verbose_name='Vigencia')),
                ('section', models.CharField(max_length=50, null=True, verbose_name='Sesión de Consejo')),
                ('means', models.CharField(max_length=100, null=True, verbose_name='Monto de Recursos')),
                ('line', models.TextField(null=True, verbose_name='Líneas de Investigación')),
                ('annual_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='researchprojects', to='production.AnnualReport')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Departament')),
                ('type_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='researchprojects', to='production.TypeReport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='researchprojects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto de Investigación',
                'verbose_name_plural': 'Listado de Proyectos de Investigación',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='PublishedLectures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título de Conferencia')),
                ('editor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre de Editor')),
                ('ed', models.CharField(max_length=200, null=True, verbose_name='Editorial (s)')),
                ('congress', models.CharField(max_length=200, verbose_name='Título de Congreso')),
                ('pages', models.CharField(max_length=15, null=True, verbose_name='Páginas')),
                ('place', models.CharField(max_length=50, verbose_name='Lugar')),
                ('editorial', models.CharField(max_length=100, null=True, verbose_name='Editorial')),
                ('type_job', models.CharField(max_length=30, null=True, verbose_name='Tipo de Investigación')),
                ('annual_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishedlectures', to='production.AnnualReport')),
                ('type_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishedlectures', to='production.TypeReport')),
                ('user', models.ManyToManyField(related_name='publishedlectures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conferencia Publicada',
                'verbose_name_plural': 'Conferencias Publicadas',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='PublishedBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título de Libro')),
                ('edition', models.CharField(max_length=100, null=True, verbose_name='Edición')),
                ('place', models.CharField(max_length=60, verbose_name='Lugar')),
                ('editorial', models.CharField(max_length=100, verbose_name='Editorial')),
                ('isbn', models.CharField(max_length=30, null=True, verbose_name='ISBN')),
                ('type_job', models.CharField(max_length=30, null=True, verbose_name='Tipo de Investigación')),
                ('annual_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishedbooks', to='production.AnnualReport')),
                ('type_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishedbooks', to='production.TypeReport')),
                ('user', models.ManyToManyField(related_name='publishedbooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Libro Publicado',
                'verbose_name_plural': 'Listado de Libros Publicados',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCollaboration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Nombre de Proyecto')),
                ('organizations', models.CharField(max_length=255, null=True, verbose_name='Organizaciones Participantes')),
                ('sector', models.CharField(max_length=20, null=True, verbose_name='Sector')),
                ('annual_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectcollaboration', to='production.AnnualReport')),
                ('type_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectcollaboration', to='production.TypeReport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectcollaboration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Listado de Colaboraciones en Proyectos',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='NewspaperPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=255, verbose_name='Título de Artículo')),
                ('newspaper_name', models.CharField(max_length=100, verbose_name='Nombre de periódico')),
                ('section', models.CharField(max_length=50, null=True, verbose_name='Sección (Letra)')),
                ('pages', models.CharField(max_length=15, null=True, verbose_name='Páginas')),
                ('type_job', models.CharField(max_length=15, null=True, verbose_name='Tipo de Trabajo')),
                ('annual_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newspaperpublication', to='production.AnnualReport')),
                ('type_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newspaperpublication', to='production.TypeReport')),
                ('user', models.ManyToManyField(related_name='newspaperpublication', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pulicación en Periódico',
                'verbose_name_plural': 'Listado de Publicaciones en Periódicos',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='MagazinePublications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Título de Arículo')),
                ('magazine_name', models.CharField(max_length=200, null=True, verbose_name='Nombre de Revista')),
                ('number', models.IntegerField(verbose_name='Número')),
                ('volume', models.CharField(max_length=15, null=True, verbose_name='Volumen')),
                ('pages', models.CharField(max_length=15, null=True, verbose_name='Páginas')),
                ('is_indexed_magazine', models.BooleanField(verbose_name='Revista Indexada')),
                ('type_job', models.CharField(max_length=200, verbose_name='Tipo de Trabajo')),
                ('annual_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magazinepublications', to='production.AnnualReport')),
                ('type_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magazinepublications', to='production.TypeReport')),
                ('user', models.ManyToManyField(related_name='magazinepublications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publicación en Revista',
                'verbose_name_plural': 'Listado de Publicaciones en Revistas',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=10, verbose_name='División')),
                ('activity', models.CharField(max_length=50, verbose_name='Actividad de Intercambio')),
                ('ies', models.CharField(max_length=250, verbose_name='Nombre de la IES')),
                ('country', models.CharField(max_length=150, verbose_name='Cuidad, País de IES')),
                ('annual_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchangeactivity', to='production.AnnualReport')),
                ('type_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchangeactivity', to='production.TypeReport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchangeactivity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad de Intercambio',
                'verbose_name_plural': 'Listado de Actividad de Intercambio',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ElectronicJournals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título de Articulo')),
                ('magazine_name', models.CharField(max_length=200, null=True, verbose_name='Nombre de Revista Electrónica')),
                ('number', models.CharField(max_length=100, null=True, verbose_name='Número')),
                ('volume', models.CharField(max_length=15, null=True, verbose_name='Volumen')),
                ('pages', models.CharField(max_length=15, null=True, verbose_name='Páginas')),
                ('doi', models.URLField(null=True, verbose_name='DOI o Ubicacion de Internet')),
                ('type_job', models.CharField(max_length=100, verbose_name='Tipo de Trabajo')),
                ('annual_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electronicjournals', to='production.AnnualReport')),
                ('type_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electronicjournals', to='production.TypeReport')),
                ('user', models.ManyToManyField(related_name='electronicjournals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revista Electrónica',
                'verbose_name_plural': 'Listado de Revistas Electrónicas',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ChaptersBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de Capítulo')),
                ('bibliographic_file', models.TextField(null=True, verbose_name='Ficha Bibliográfica de Libro')),
                ('annual_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chaptersbooks', to='production.AnnualReport')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Departament')),
                ('type_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chaptersbooks', to='production.TypeReport')),
                ('user', models.ManyToManyField(related_name='chaptersbooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Capítulo de Libro',
                'verbose_name_plural': 'Listado de Capítulos',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='BookReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título de Reseña')),
                ('book', models.CharField(max_length=200, verbose_name='Título de Libro')),
                ('publication', models.CharField(max_length=200, verbose_name='Título de Publicación')),
                ('number', models.CharField(max_length=100, null=True, verbose_name='Número')),
                ('volume', models.CharField(max_length=15, null=True, verbose_name='Volumen')),
                ('pages', models.CharField(max_length=15, null=True, verbose_name='Páginas')),
                ('annual_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookreviews', to='production.AnnualReport')),
                ('type_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookreviews', to='production.TypeReport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookreviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reseña de Libro',
                'verbose_name_plural': 'Listado de Reseñas de Libros',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='AcademicEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Nombre de Evento')),
                ('institute', models.CharField(max_length=250, null=True, verbose_name='Institución Sede')),
                ('country', models.CharField(max_length=100, null=True, verbose_name='Cuidad/Paía')),
                ('range_date', models.CharField(max_length=100, null=True, verbose_name='Rango de Fechas')),
                ('type_activity', models.CharField(max_length=255, verbose_name='Tipo de Actividad')),
                ('annual_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academicevents', to='production.AnnualReport')),
                ('type_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academicevents', to='production.TypeReport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academicevents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento Acádemico',
                'verbose_name_plural': 'Listado de Eventos Acádemicos',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='AcademicCollaboration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de Red Acádemica')),
                ('institutions', models.TextField(verbose_name='Instituciones Pertenecientes a la Red')),
                ('activities', models.TextField(null=True, verbose_name='Actividades Destacadas')),
                ('annual_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academiccollaboration', to='production.AnnualReport')),
                ('type_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academiccollaboration', to='production.TypeReport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academiccollaboration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Red de Colaboración',
                'verbose_name_plural': 'Listado de Redes de Colaboración Acádemica',
                'ordering': ['pk'],
            },
        ),
    ]
