# Generated by Django 2.2.12 on 2021-03-27 01:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_auto_20210325_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazinepublications',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='magazinepublications', to=settings.AUTH_USER_MODEL),
        ),
    ]
