# Generated by Django 2.2.12 on 2021-03-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_auto_20210326_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazinepublications',
            name='number',
            field=models.IntegerField(null=True, verbose_name='Número'),
        ),
    ]
