# Generated by Django 2.2.12 on 2021-03-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_auto_20210326_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazinepublications',
            name='pages',
            field=models.CharField(max_length=50, null=True, verbose_name='Páginas'),
        ),
        migrations.AlterField(
            model_name='magazinepublications',
            name='volume',
            field=models.CharField(max_length=50, null=True, verbose_name='Volumen'),
        ),
    ]
