# Generated by Django 2.2.12 on 2021-03-27 02:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_auto_20210326_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unpublishedlectures',
            options={'ordering': ['pk'], 'verbose_name': 'Conferencia No Publicada', 'verbose_name_plural': 'Listado de Conferencias no Publicadas'},
        ),
        migrations.AlterField(
            model_name='magazinepublications',
            name='user',
            field=models.ManyToManyField(related_name='magazinepublications', to=settings.AUTH_USER_MODEL),
        ),
    ]
