# Generated by Django 2.2.12 on 2021-03-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_auto_20210326_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chaptersbooks',
            options={'ordering': ['pk'], 'verbose_name': 'Capítulo de Libro', 'verbose_name_plural': 'Listado de Capítulos de Libros'},
        ),
        migrations.AlterModelOptions(
            name='publishedlectures',
            options={'ordering': ['pk'], 'verbose_name': 'Conferencia Publicada', 'verbose_name_plural': 'Listado de Conferencias Publicadas'},
        ),
        migrations.AddField(
            model_name='unpublishedlectures',
            name='present',
            field=models.CharField(default='', max_length=200, verbose_name='Lugar de Presentación de Conferencia'),
        ),
    ]
