# Generated by Django 2.2.12 on 2021-03-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_auto_20210327_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unpublishedlectures',
            name='congress',
            field=models.CharField(max_length=200, null=True, verbose_name='Nombre de Congreso'),
        ),
    ]
