# Generated by Django 2.2.12 on 2021-03-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_auto_20210327_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unpublishedlectures',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='unpublishedlectures',
            name='country',
            field=models.CharField(max_length=50, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='unpublishedlectures',
            name='type_job',
            field=models.CharField(max_length=100, null=True, verbose_name='Tipo de Investigación'),
        ),
    ]
