from django.urls import path

from . import views

urlpatterns = [
    path('request-scholarship/',
         views.RequestScholarshipView.as_view(), name='request-scholarship'),
    path('dictum-scholarship/<int:pk>/',
         views.DictumScholarshipView.as_view(), name='dictum-scholarship'),
    path('receipt-dictum-scholarship/<int:pk>/',
         views.ReceiptDictumScholarshipView.as_view(), name='dictum-scholarship'),
    path('notification-scholarship/<int:pk>/',
         views.NotificationScholarsView.as_view(), name='notification-scholarship'),
    path('resolution-scholarship/<int:pk>/',
         views.ResolutionScholarsView.as_view(), name='resolution-scholarship'),
    path('reply-scholarship/<int:pk>/',
         views.ReplyScholarsView.as_view(), name='reply-scholarship'),
    path('bis-scholarship/<int:pk>/',
         views.BISScholarsView.as_view(), name='bis-scholarship'),
    path('receipt-bis-scholarship/<int:pk>/',
         views.ReceiptBisScholarsView.as_view(), name='receipt-bis-scholarship'),
    path('list-scholarship-year/<int:year>/<int:op>/',
         views.RequestScholarshipListYear.as_view(), name='list-scholarship-year'),
    path('list-scholarship-number/<str:number>/<int:op>/',
         views.RequestScholarshipListNumber.as_view(), name='list-scholarship-number'),
    path('retrieve-scholarship/<int:pk>/',
         views.RequestScholarshipRetrieve.as_view(), name='retrieve-scholarship'),
    path('list-option-requests/',
         views.OptionRequestList.as_view(), name='list-option'),
    path('finalized-scholarship/<int:pk>/',
         views.FinalizedScholarshipView.as_view(), name='finalize-scholarship'),
    path('deleted-scholarship/<int:pk>/',
         views.DeleteScholarshipView.as_view(), name='delete-scholarship'),
    path('set-result-scholarship/<int:pk>/',
         views.ResultScholarshipView.as_view(), name='result-scholarship'),
    path('additional-file-scholarship/',
         views.AdditionalFilesView.as_view(), name='additional-file'),
    path('list-file-additional/<int:pk>/',
         views.AdditionalFilesList.as_view(), name='list-additional-file'),
    path('delete-file-additional/<int:pk>/',
         views.DeleteAdditionalFileView.as_view(), name='delete-file-additional'),
]
