# Generated by Django 2.2.12 on 2020-12-18 00:26

import api.academic.utils
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='AcademicStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_in_classroom', models.IntegerField()),
                ('hour_in_classroom', models.IntegerField()),
                ('student_in_classroom', models.IntegerField()),
                ('course_out_classroom', models.IntegerField()),
                ('hour_out_classroom', models.IntegerField()),
                ('student_out_classroom', models.IntegerField()),
                ('trimester', models.CharField(choices=[('Primer', 'Primer'), ('Segundo', 'Segundo'), ('Tercer', 'Tercer')], max_length=15)),
                ('year', models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(2000), api.academic.utils.max_value_current_year])),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Departament')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Trimestre',
                'verbose_name_plural': 'Registros por Trimestre',
            },
        ),
    ]
