# Generated by Django 2.2.12 on 2020-12-20 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan de Estudio',
                'verbose_name_plural': 'Planes de Estudio',
            },
        ),
        migrations.AlterField(
            model_name='academicstatistics',
            name='departament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.Departament'),
        ),
        migrations.AddField(
            model_name='academicstatistics',
            name='study_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.StudyPlan'),
        ),
    ]
