# Generated by Django 2.2.12 on 2020-12-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_auto_20201220_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicstatistics',
            name='course_in_classroom',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='academicstatistics',
            name='course_out_classroom',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='academicstatistics',
            name='hour_in_classroom',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='academicstatistics',
            name='hour_out_classroom',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='academicstatistics',
            name='student_in_classroom',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='academicstatistics',
            name='student_out_classroom',
            field=models.FloatField(),
        ),
    ]
