# Generated by Django 2.2.12 on 2020-12-20 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_auto_20201220_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicstatistics',
            options={'ordering': ['pk'], 'verbose_name': 'Registro de Trimestre', 'verbose_name_plural': 'Registros por Trimestre'},
        ),
    ]
