# Generated by Django 2.2.12 on 2020-12-24 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_academicstatisticstotals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicstatisticstotals',
            name='academics',
        ),
        migrations.AddField(
            model_name='academicstatistics',
            name='totals',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.AcademicStatisticsTotals'),
        ),
    ]
