# Generated by Django 2.2.12 on 2020-12-24 00:09

import api.academic.utils
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0008_auto_20201223_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicstatisticstotals',
            name='departament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.Departament'),
        ),
        migrations.AddField(
            model_name='academicstatisticstotals',
            name='study_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.StudyPlan'),
        ),
        migrations.AddField(
            model_name='academicstatisticstotals',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicstatisticstotals',
            name='year',
            field=models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(2000), api.academic.utils.max_value_current_year]),
        ),
        migrations.AlterField(
            model_name='academicstatisticstotals',
            name='course_in_classroom',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='academicstatisticstotals',
            name='course_out_classroom',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='academicstatisticstotals',
            name='hour_in_classroom',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='academicstatisticstotals',
            name='hour_out_classroom',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='academicstatisticstotals',
            name='student_in_classroom',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='academicstatisticstotals',
            name='student_out_classroom',
            field=models.FloatField(default=0.0),
        ),
    ]
