# Generated by Django 2.2.12 on 2020-12-24 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_auto_20201223_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicStatisticsTotals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_in_classroom', models.FloatField()),
                ('hour_in_classroom', models.FloatField()),
                ('student_in_classroom', models.FloatField()),
                ('course_out_classroom', models.FloatField()),
                ('hour_out_classroom', models.FloatField()),
                ('student_out_classroom', models.FloatField()),
                ('academics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='totals', to='academic.AcademicStatistics')),
            ],
            options={
                'verbose_name': 'Estadisticas Totales de Usuario Por Año',
                'verbose_name_plural': 'Estadisticas Totales Por Año',
            },
        ),
    ]
