# Generated by Django 2.2.12 on 2020-12-24 00:48

import api.academic.utils
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0011_academicstatisticstotals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicstatisticstotals',
            name='academics',
        ),
        migrations.AddField(
            model_name='academicstatistics',
            name='totals',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.AcademicStatisticsTotals'),
        ),
        migrations.AddField(
            model_name='academicstatisticstotals',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='academicstatisticstotals',
            name='departament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.Departament'),
        ),
        migrations.AddField(
            model_name='academicstatisticstotals',
            name='study_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.StudyPlan'),
        ),
        migrations.AddField(
            model_name='academicstatisticstotals',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicstatisticstotals',
            name='year',
            field=models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(2000), api.academic.utils.max_value_current_year]),
        ),
    ]
