# Generated by Django 2.2.12 on 2021-01-13 19:41

import api.academic.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0014_auto_20201223_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicstatisticstotals',
            options={'ordering': ['pk'], 'verbose_name': 'Estadisticas Totales de Usuario Por Año', 'verbose_name_plural': 'Estadisticas Totales Por Año'},
        ),
        migrations.AlterModelOptions(
            name='departament',
            options={'ordering': ['name'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='studyplan',
            options={'ordering': ['name'], 'verbose_name': 'Plan de Estudio', 'verbose_name_plural': 'Planes de Estudio'},
        ),
        migrations.AlterField(
            model_name='academicstatistics',
            name='year',
            field=models.PositiveIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(2000), api.academic.utils.max_value_current_year]),
        ),
        migrations.AlterField(
            model_name='academicstatisticstotals',
            name='year',
            field=models.PositiveIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(2000), api.academic.utils.max_value_current_year]),
        ),
    ]
