# Generated by Django 2.2.12 on 2021-01-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0015_auto_20210113_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicstatistics',
            name='trimester',
            field=models.CharField(choices=[('Invierno', 'Invierno'), ('Primavera', 'Primavera'), ('Otoño', 'Otoño')], max_length=15),
        ),
    ]
