# Generated by Django 2.2.12 on 2021-02-05 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0016_auto_20210121_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos Existentes',
                'ordering': ['pk'],
            },
        ),
        migrations.RenameField(
            model_name='academicstatistics',
            old_name='course_in_classroom',
            new_name='number_course',
        ),
        migrations.RenameField(
            model_name='academicstatistics',
            old_name='course_out_classroom',
            new_name='number_hour',
        ),
        migrations.RenameField(
            model_name='academicstatistics',
            old_name='hour_in_classroom',
            new_name='number_student',
        ),
        migrations.RemoveField(
            model_name='academicstatistics',
            name='hour_out_classroom',
        ),
        migrations.RemoveField(
            model_name='academicstatistics',
            name='student_in_classroom',
        ),
        migrations.RemoveField(
            model_name='academicstatistics',
            name='student_out_classroom',
        ),
        migrations.AddField(
            model_name='academicstatistics',
            name='classroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='academicstatistics',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.Course'),
        ),
    ]
