# Generated by Django 2.2.12 on 2021-01-13 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(choices=[('Hi', 'HI'), ('FIN', 'FIN')], max_length=255, verbose_name='¿Que Solicita?')),
                ('date_request', models.DateField(verbose_name='Fecha de Solicitud')),
                ('number_request', models.CharField(max_length=15, verbose_name='Número de Solicitud')),
                ('file_request', models.FileField(upload_to='', verbose_name='Archivo de Solicitud')),
                ('date_send_request', models.DateField(blank=True, null=True, verbose_name='Fecha de envío a la dictaminadora')),
                ('date_get_request', models.DateField(blank=True, null=True, verbose_name='Fecha de respuesta')),
                ('number_dictum', models.CharField(blank=True, max_length=20, null=True, verbose_name='Folio de dictamen')),
                ('file_dictum', models.FileField(blank=True, null=True, upload_to='', verbose_name='Archivo de Dictamen')),
                ('number_notification', models.CharField(blank=True, max_length=20, null=True, verbose_name='Folio de Notificación de Recepción')),
                ('file_notification', models.FileField(blank=True, null=True, upload_to='', verbose_name='Archivo de Notificación de Recepción')),
                ('number_resolution', models.CharField(blank=True, max_length=20, null=True, verbose_name='Folio de Resolución')),
                ('file_resolution', models.FileField(blank=True, null=True, upload_to='', verbose_name='Archivo de Resolución')),
                ('number_reply', models.CharField(blank=True, max_length=20, null=True, verbose_name='Folio de Respuesta de Comisión Dictaminadora')),
                ('file_reply', models.FileField(blank=True, null=True, upload_to='', verbose_name='Archivo de Respuesta de Comisión Dictaminadora')),
                ('number_reply_dictum', models.CharField(blank=True, max_length=20, null=True, verbose_name='Folio de Dictamen BIS')),
                ('file_reply_dictum', models.FileField(blank=True, null=True, upload_to='', verbose_name='Archivo de Dictamen BIS')),
                ('number_receipt', models.CharField(blank=True, max_length=20, null=True, verbose_name='Folio de Acuse de Recibido de Dictamen')),
                ('file_receipt', models.FileField(blank=True, null=True, upload_to='', verbose_name='Archivo de Acuse de Recibido de Dictament')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Beca',
                'verbose_name_plural': 'Solicitudes de Beca',
            },
        ),
    ]
