# Generated by Django 2.2.12 on 2021-01-13 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0002_auto_20210113_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optionrequest',
            options={'verbose_name': 'Opción de Solicitud', 'verbose_name_plural': 'Opciones para Solicitud de Becas'},
        ),
    ]
