# Generated by Django 2.2.12 on 2021-01-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0003_auto_20210113_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='file_dictum',
            field=models.FileField(blank=True, null=True, upload_to='dictum/', verbose_name='Archivo de Dictamen'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='file_notification',
            field=models.FileField(blank=True, null=True, upload_to='notification/', verbose_name='Archivo de Notificación de Recepción'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='file_receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipt/', verbose_name='Archivo de Acuse de Recibido de Dictament'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='file_reply',
            field=models.FileField(blank=True, null=True, upload_to='reply/', verbose_name='Archivo de Respuesta de Comisión Dictaminadora'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='file_reply_dictum',
            field=models.FileField(blank=True, null=True, upload_to='reply_dictum/', verbose_name='Archivo de Dictamen BIS'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='file_request',
            field=models.FileField(upload_to='request/', verbose_name='Archivo de Solicitud'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='file_resolution',
            field=models.FileField(blank=True, null=True, upload_to='resolution/', verbose_name='Archivo de Resolución'),
        ),
    ]
