# Generated by Django 2.2.12 on 2021-01-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0004_auto_20210114_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='file_request',
            field=models.CharField(max_length=100, verbose_name='Archivo de Solicitud'),
        ),
    ]
