# Generated by Django 2.2.12 on 2021-01-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0005_auto_20210114_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='file_dictum',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Archivo de Dictamen'),
        ),
    ]
