# Generated by Django 2.2.12 on 2021-01-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0006_auto_20210114_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='file_receipt_dictum',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Archivo de Acuse'),
        ),
    ]
