# Generated by Django 2.2.12 on 2021-01-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0007_scholarship_file_receipt_dictum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='file_notification',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Archivo de Notificación de Recepción'),
        ),
    ]
