# Generated by Django 2.2.12 on 2021-01-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0009_auto_20210114_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='year',
            field=models.IntegerField(default=2020),
        ),
    ]
