# Generated by Django 2.2.12 on 2021-01-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0010_scholarship_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='file_reply_dictum',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Archivo de Dictamen BIS'),
        ),
    ]
