# Generated by Django 2.2.12 on 2021-01-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0012_auto_20210114_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='file_reply_dictum',
            new_name='file_bis',
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='number_reply_dictum',
            new_name='number_bis',
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='number_receipt',
            new_name='number_receipt_bis',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='file_receipt',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='file_receipt_bis',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Archivo de Acuse de Recibido de Dictament'),
        ),
    ]
