# Generated by Django 2.2.12 on 2021-01-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0013_auto_20210114_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optionrequest',
            options={'ordering': ['pk'], 'verbose_name': 'Opción de Solicitud', 'verbose_name_plural': 'Opciones para Solicitud de Becas'},
        ),
        migrations.AlterModelOptions(
            name='scholarship',
            options={'ordering': ['date_request'], 'verbose_name': 'Solicitud de Beca', 'verbose_name_plural': 'Solicitudes de Beca'},
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='date_get_request',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='date_request',
            field=models.DateTimeField(verbose_name='Fecha de Solicitud'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='date_send_request',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío a la dictaminadora'),
        ),
    ]
