# Generated by Django 2.2.12 on 2021-01-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0017_scholarship_number_receipt_dictum'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='file_dictum',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Archivo de Acuse de Dictamen'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='number_receipt_dictum',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Folio de Acuse de Dictamen'),
        ),
    ]
