# Generated by Django 2.2.12 on 2021-01-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0018_auto_20210119_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='request',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='permanence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='promotion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='stimulus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='trajectory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='years',
            field=models.IntegerField(default=0),
        ),
    ]
