# Generated by Django 2.2.12 on 2021-01-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0019_auto_20210125_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
