# Generated by Django 2.2.12 on 2021-01-30 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0024_additionalfiles_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalfiles',
            name='is_active',
        ),
    ]
